crossbar: fix crossbar package installation issue
drop "crossbar/worker/test" inroder to fix the package installation
issue, these tests are not required during package installation.
without this change we get below package installation error

log:
/usr/lib/python2.7/dist-packages/crossbar/worker/test/examples/
syntaxerror.py", line 33
class # noqa
^
SyntaxError: invalid syntax

dpkg: error processing package python-crossbar (--configure):
subprocess installed post-installation script returned error exit
status 101

Signed-off-by: Shrikant Bobade <Shrikant_Bobade@mentor.com>